In [2]:
from sklearn.preprocessing import StandardScaler

In [3]:
import numpy as np


In [4]:
a = np.random.randint(0,10,100)

In [5]:
a

array([8, 7, 8, 7, 5, 6, 9, 5, 5, 9, 7, 7, 7, 8, 2, 0, 0, 5, 1, 6, 8, 4,
       3, 2, 6, 3, 9, 8, 7, 6, 1, 0, 0, 2, 3, 9, 3, 3, 5, 0, 4, 6, 8, 1,
       6, 0, 9, 8, 8, 3, 8, 2, 3, 1, 4, 0, 7, 8, 7, 3, 6, 0, 3, 1, 9, 2,
       8, 1, 7, 7, 0, 9, 9, 6, 8, 9, 6, 4, 4, 1, 7, 3, 1, 0, 9, 6, 5, 7,
       8, 6, 6, 6, 6, 1, 9, 7, 3, 4, 7, 6])

NameError: name 'scaler' is not defined

In [7]:
scaler = StandardScaler()

In [8]:
scaler.fit(a)

ValueError: Expected 2D array, got 1D array instead:
array=[8. 7. 8. 7. 5. 6. 9. 5. 5. 9. 7. 7. 7. 8. 2. 0. 0. 5. 1. 6. 8. 4. 3. 2.
 6. 3. 9. 8. 7. 6. 1. 0. 0. 2. 3. 9. 3. 3. 5. 0. 4. 6. 8. 1. 6. 0. 9. 8.
 8. 3. 8. 2. 3. 1. 4. 0. 7. 8. 7. 3. 6. 0. 3. 1. 9. 2. 8. 1. 7. 7. 0. 9.
 9. 6. 8. 9. 6. 4. 4. 1. 7. 3. 1. 0. 9. 6. 5. 7. 8. 6. 6. 6. 6. 1. 9. 7.
 3. 4. 7. 6.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [12]:
a = a.reshape(-1,1)

In [17]:
scaler.fit(a)

StandardScaler()

In [15]:
scaler

StandardScaler()

In [18]:
scaler.mean_

array([4.97])

In [19]:
scaler.var_

array([8.5291])

In [20]:
a.shape

(100, 1)

In [23]:
scaler.transform(a)

array([[ 1.03750698],
       [ 0.69509543],
       [ 1.03750698],
       [ 0.69509543],
       [ 0.01027235],
       [ 0.35268389],
       [ 1.37991852],
       [ 0.01027235],
       [ 0.01027235],
       [ 1.37991852],
       [ 0.69509543],
       [ 0.69509543],
       [ 0.69509543],
       [ 1.03750698],
       [-1.01696228],
       [-1.70178537],
       [-1.70178537],
       [ 0.01027235],
       [-1.35937383],
       [ 0.35268389],
       [ 1.03750698],
       [-0.3321392 ],
       [-0.67455074],
       [-1.01696228],
       [ 0.35268389],
       [-0.67455074],
       [ 1.37991852],
       [ 1.03750698],
       [ 0.69509543],
       [ 0.35268389],
       [-1.35937383],
       [-1.70178537],
       [-1.70178537],
       [-1.01696228],
       [-0.67455074],
       [ 1.37991852],
       [-0.67455074],
       [-0.67455074],
       [ 0.01027235],
       [-1.70178537],
       [-0.3321392 ],
       [ 0.35268389],
       [ 1.03750698],
       [-1.35937383],
       [ 0.35268389],
       [-1

In [24]:
dir(scaler)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_check_n_features',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_reset',
 '_validate_data',
 'copy',
 'fit',
 'fit_transform',
 'get_params',
 'inverse_transform',
 'mean_',
 'n_features_in_',
 'n_samples_seen_',
 'partial_fit',
 'scale_',
 'set_params',
 'transform',
 'var_',
 'with_mean',
 'with_std']

In [25]:
scaler.fit_transform(a)

array([[ 1.03750698],
       [ 0.69509543],
       [ 1.03750698],
       [ 0.69509543],
       [ 0.01027235],
       [ 0.35268389],
       [ 1.37991852],
       [ 0.01027235],
       [ 0.01027235],
       [ 1.37991852],
       [ 0.69509543],
       [ 0.69509543],
       [ 0.69509543],
       [ 1.03750698],
       [-1.01696228],
       [-1.70178537],
       [-1.70178537],
       [ 0.01027235],
       [-1.35937383],
       [ 0.35268389],
       [ 1.03750698],
       [-0.3321392 ],
       [-0.67455074],
       [-1.01696228],
       [ 0.35268389],
       [-0.67455074],
       [ 1.37991852],
       [ 1.03750698],
       [ 0.69509543],
       [ 0.35268389],
       [-1.35937383],
       [-1.70178537],
       [-1.70178537],
       [-1.01696228],
       [-0.67455074],
       [ 1.37991852],
       [-0.67455074],
       [-0.67455074],
       [ 0.01027235],
       [-1.70178537],
       [-0.3321392 ],
       [ 0.35268389],
       [ 1.03750698],
       [-1.35937383],
       [ 0.35268389],
       [-1