## Linear Algebra Quiz #3

![title](./img/3_0.jpeg)

We strongly suggest working with numpy :)

In [1]:
#Do your imports here
import numpy as np 
import math 


![title](./img/3_2.png)
![title](./img/3_3.png)
Create a program that can output

- What is the value of element c23​ of Matrix C where C=A x B ?
- What is the value of element c23​ of Matrix C where C=B x A ?

In [5]:
def mult(A,B):
    return np.dot(A,B)
A = np.array([0.6,-15,2,5,98])
B = np.array([[2,2,-4],[9,-14,0],[13,-0.5,44],[1,9,4],[0,0,5]])
mult(A,B)
#You can not multiply 5*3 matrix with 1*5 matrix

array([-102.8,  255.2,  595.6])

In [30]:
# okay numpy is great but... how would you inverse a matrix by hand?

def inverse_matrix(A):
    I = np.eye(A.shape[0])
    print(I)
    return I/A
A = np.array([0.6,-15,2,5,98])
inverse_matrix(A)
# A*B

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


array([[ 1.66666667, -0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.06666667,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.        ,  0.5       ,  0.        ,  0.        ],
       [ 0.        , -0.        ,  0.        ,  0.2       ,  0.        ],
       [ 0.        , -0.        ,  0.        ,  0.        ,  0.01020408]])

![title](./img/3_1.png)
Create a program that can output

- What is the value of the ijth element if i = 2 and j=3?
- What is the value of the ijth element if i = 3 and j=1?

In [ ]:
# Just answer using code --> easy stuff!

# Harder
# Can you build a matrix solver that can do output the result given n matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed. 

![title](./img/3_3.png)
Create a program that can output
- How many rows will C have?
- How many columns will C have?
- What will be the value of c13​?